# version: '5.0'

services:
  postgresdbml:
    image: postgres:15-alpine
    container_name: postgresMLProd
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - $DB_PORT:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  ml-agua-app:
    build:
      context: .
      dockerfile: Dockerfile.prod  # Usamos el Dockerfile de producción
    container_name: nestMLProd
    env_file: .env
    depends_on:
      - postgresdbml
    ports:
      - $PORT:$PORT
volumes:
  db_data:

# Ejecutar en produccion
# docker-compose -f docker-compose.prod.yml up --build -d

# Para ver log en CapRover:
# docker service logs srv-captain--ml-agua-app --since 60m --follow
