# version: '5.0'

services:
  postgresdbml:
    image: postgres:16-alpine
    container_name: postgresML
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - $DB_PORT:5432
    volumes:
      - db_data_ml:/var/lib/postgresql/data

  ml-agua-app:
    build: .
    container_name: nestML
    env_file: .env
    depends_on:
      - postgresdbml
    # links:
    #   - postgresdbml
    volumes:
      - .:/backendMosojLlajta
      - /backendMosojLlajta/node_modules
    ports:
      - $PORT:$PORT
volumes:
  db_data_ml:


# docker exec -it nestSevenApp sh
