# version: '5.0'

services:
  mysqldbml:
    image: mysql
    container_name: mysqlML
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD_ROOT
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    ports:
      - $DB_PORT:$DB_PORT

  ml-agua-app:
    build: .
    container_name: nestML
    env_file: .env
    depends_on:
      - mysqldbml
    # links:
    #   - mysqldbml
    volumes:
      - .:/backendMosojLlajta
      # - /backendMosojLlajta/node_modules
    ports:
      - $PORT:$PORT
volumes:
  db_data_ml:


# docker exec -it nestSevenApp sh
